version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: N1H4dg3q01
      MYSQL_DATABASE: winter_market
    ports:
      - "3308:3306"
